### PR TITLE
Support trait

### PR DESCRIPTION
**Pull request by yongpingchen**
### Brief introduction
Trait is introduced in Thing-IF. Mobile App can provide trait alias for action, and state. To use trait, firstly developers need define thingType,  firmware version, trait, trait version and trait alias in Developer Portal or through REST APIs. 

Trait is not mandatory, after update to new version of SDK, non-trait supported thing can still be used.

Main changes to support Trait in SDK.
  - `schema` and `schemaVersion` are removed when posting new command or posting/patching command trigger
  -  trait alias can be provided in action of command when posting new command or posting/patching command trigger. 

   ```
     var traiAlias = "BasicFeaturesAlias";
     var anotherAlias = "LightAlias"
     var actions = [
         {"BasicFeaturesAlias":[{"turnPower": true}]}, 
         {"LigthAlias":[
             {"setRed": 12}, 
             {"setGreen": 100}, 
             {"setBlue": 100}
            ]
         }
     ];
     var request = new ThingIF.PostCommandRequest(actions);
     api.postNewCommand(request).then(function(command) {		
         // Do something	
      }).catch(function(err){
      });
   ```

  - state in condition can be provided with trait alias. 

   ```
     var traitAlias = "BasicFeatureAlias";
     var actions = [{traitAlias: [{"turnPower": true}]}];
     var commandTargetID = new ThingIF.TypedID(ThingIF.Types.Thing, "another thing to receive command");
     var condition = new ThingIF.Condition(new ThingIF.Equals("power", "false", traitAlias));
     var statePredicate = new ThingIF.StatePredicate(condition, ThingIF.TriggersWhen.CONDITION_CHANGED);
     var triggerCommandObject = new ThingIF.TriggerCommandObject(actions, commandTargetID);
     var request = new ThingIF.PostCommandTriggerRequest(triggerCommandObject, statePredicate);
     api.postCommandTrigger(request).then(function(trigger) {
       // Do something
     }).catch(function(err){
       // Error handling
     });
   ```
  - Add history state query APIs for trait support and non trait support.
  - update firmware version of thing.
  - update thingType of thing to use trait
  - fetch current state through trait alias.

### Out of scope
- define trait and trait version. 
- define thing type and firmware version. 
- define trait alias(trait, trait version, thing type, and firmware version). 
- get trait alias for the thing type and firmware version. 

### Changes
 - Condition relative
   - Equals: add alias(nullable)
   - NotEquals: add alias(nullable)
   - Range: add alias(nullable)
     - Range#greaterThan add alias
     - Range#greaterThanEquals add alias
     - Range#lessThan add alias
     - Range#lessThanEquals add alias
 - PostCommandRequest: remove schema and schema version
 - TriggerCommandObject: remove schema and schema version 
 - Add ThingIFAPI/APIAuthor#updateFirmwareversion to enable to update firmware version of thing
 - query history state
   - add QueryHistoryStatesRequest
   - add Aggregation and AggregationType to constructor aggregation condition
   - add TimeRange clause for `withTimeRange` query
   - add GroupedResults and HistoryStateResults to represent result of query
   - add ThingIFAPI/APIAuthor#queryStates to enable history states query
 - start to use trait
   - add ThingIFAPI/APIAuthor#updateThingType to using trait
 - add nullable `alias` parameter to ThingIFAPI/APIAuthor#getState to enable get state by alias

### Backward compatibility 
Trait is not mandatory, in this sense it is compatibility. However, the schema and schema version are removed, so after update SDK, need to change parameters for PostCommandRequest, TriggerCommandObject

### CODE REVIEW

**Comment by satoshikumano** [comment]
Can you add change summry describes which API has been modified/ Added.

**Comment by yongpingchen** [comment]
@satoshikumano detail changes are added.

**Comment by yongpingchen** [comment]
Add api to update firmware version

**Comment by yongpingchen** [comment]
The snippets list here https://github.com/KiiPlatform/thing-if-JSSDK/wiki/Support-Trait

**Comment by yongpingchen** [comment]
@satoshikumano please confirm

**Comment by yongpingchen** [comment]
No include in the design:
- Aggregation response in the history sate query result
- List ungrouped history state with bestEffortLimit and paginationKey

**Pull request closed without merging**
