### PR TITLE
Thing State History

### PR DESCRIPTION
**Pull request by yongpingchen**
Enable thing state history and improve onboarding options
## New Class
- DataGroupingInterval
- LayoutPosition

## Improvement
- OnboardWithVendorThingIDRequest
  - add `firmwareVersion`
  - add `dataGroupingInterval`
  - add `layoutPosition`
- OnboardWithThingIDRequest
  - add `dataGroupingInterval`
  - add `layoutPosition`

### CODE REVIEW

**Comment by yongpingchen** [comment]
@nfukuzaki can you have a internal review of API design?

**Comment by nfukuzaki** [comment]
LGTM

**Comment by yongpingchen** [comment]
@nfukuzaki can you review the implementation?

**Comment by nfukuzaki** [comment]
LGTM

**Pull request merged**
